FIND_PATH(OSET_CREDIS_INCLUDE_DIRS 
NAMES
    credis.h
PATHS
    #/usr/local/install/oset/mods/m_credis/include
	${CMAKE_INSTALL_PREFIX}/install/oset/mods/m_credis/include
)

find_library(OSET_CREDIS_LIBRARIES
NAMES 
    oset-credis
PATHS 
	#/usr/local/install/oset/lib
	${CMAKE_INSTALL_PREFIX}/install/oset/lib
)

mark_as_advanced(OSET_CREDIS_INCLUDE_DIRS OSET_CREDIS_LIBRARIES)


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSET-CREDIS DEFAULT_MSG OSET_CREDIS_INCLUDE_DIRS OSET_CREDIS_LIBRARIES)

IF(OSET_FOUND)
   SET( OSET_CREDIS_LIBRARIES ${OSET_CREDIS_LIBRARIES})
ELSE(OSET_FOUND)
   SET( OSET_CREDIS_LIBRARIES )
ENDIF(OSET_FOUND)
message (STATUS "OSET-HIREDIS found: YES ${OSET_CREDIS_INCLUDE_DIRS} ${OSET_CREDIS_LIBRARIES}")