FIND_PATH(OSET_ESL_INCLUDE_DIRS 
NAMES
    esl.h
PATHS
	#/usr/local/install/oset/esl/include
	${CMAKE_INSTALL_PREFIX}/install/oset/esl/include
)

find_library(OSET_ESL_LIBRARIES
NAMES 
    oset-esl
PATHS 
	#/usr/local/install/oset/lib
	${CMAKE_INSTALL_PREFIX}/install/oset/lib
)

mark_as_advanced(OSET_ESL_INCLUDE_DIRS OSET_ESL_LIBRARIES)


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSET-ESL DEFAULT_MSG OSET_ESL_INCLUDE_DIRS OSET_ESL_LIBRARIES)

IF(OSET_FOUND)
   SET( OSET_ESL_LIBRARIES ${OSET_ESL_LIBRARIES})
ELSE(OSET_FOUND)
   SET( OSET_ESL_LIBRARIES )
ENDIF(OSET_FOUND)
message (STATUS "OSET-ESL found: YES ${OSET_ESL_INCLUDE_DIRS} ${OSET_ESL_LIBRARIES}")